version: '3'
services:
  mysql_db_shoes:
    image: mysql
    container_name: mysql_db_shoes
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - mysql_db_shoes:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db_shoes
    build: .
    container_name: cons-deploy-shoes
    env_file: .env
    environment:
      - DB_HOST=mysql_db_shoes
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_DIALECT=$DB_DIALECT
    ports:
      - "9090:8080"
    networks:
      - node-network
volumes:
  mysql_db_shoes:
    driver: local
networks:
  node-network: